import { QuizItemsSchema } from '@repo/schema/paper'

export const MOCK_PAPER = QuizItemsSchema.parse([
    {
        "text": "<h2>Are You Ready to Hug a Robot?</h2><p>Getting hugged tends to be a powerful positive emotional experience. Hugs have been shown to enhance social bonding and emotional well-being. However, not everyone can get a hug <code>whenever/when</code> they need one. Some people are lonely and do not have anyone to hug them. Others may be in long-distance relationships <code>where/so</code> it is not easy to get physical affection from their partner. In this case, they <code>may/might</code> receive fewer hugs than they like. How can this problem be solved? <code>What</code> scientists have proposed is to develop hug robots. This could offer lonely people the positive effects of getting hugged without the need <code>to seek</code> a person who could hug them. Nevertheless, designing a hug robot is not an easy task. For example, if the robot is very large and made mostly of metal, people might be frightened of it, <code>instead of/rather than</code> happily hugging it. Therefore, psychological research is needed.</p><p>A new study, which <code>has been published</code> in International Journal recently, focuses on the development of Moffuly-II, a newly developed hug robot, which can move its arms to perform different small gestures during the hug. When two people hug, they often do specific things with their hands, such as clapping the <code>hugged</code> person on the back to signal sympathy. It is important that a hug robot can perform similar gestures, too. In the study, the scientists wanted to know whether these gestures would make a robot hug <code>more appealing</code>. Volunteers who Moffully-II hugged generally preferred hugs with gestures to gesture-less hugs. They felt that the robot was more friendly when <code>performing</code> gestures.</p><p>The findings of the study indicate that it is possible to design a robot that people enjoy to hug. Details matter here, as the intra-hug gestures played a significant role in determining how much the human volunteers enjoyed the hug.</p>",
        "type": "grammar",
        "hints": {
            "to seek": "seek",
            "has been published": "publish",
            "hugged": "hug",
            "more appealing": "appealing",
            "performing": "perform"
        },
        "id": "ev4jM"
    },
    {
        "text": "<h2>Chinese animations(动画) are booming</h2><p>The “Black Cat Detective\", released 40 years ago, was a childhood favorite for many Chinese. Since then, Chinese cartoons have come a long way. While “Black Cat Detective\" was simply drawn, current cartoons feature <code>technical</code> advances and fascinating plots. One example is “Boonie Bears: Time Twist\", a family-friendly adventure released in February, with smooth animation reminding us of Pixar, a <code>pioneering</code> animation studio now owned by Disney. These recent <code>leaps</code> in quality have enabled Chinese cartoons to succeed at the domestic box office. “Ne Zha: Birth of the Demon Child\" was the most well-received film in China in 2019, <code>unexpectedly</code> beating out \"Avengers: Endgame\", a superhero movie by Marvel Studios.</p><p>In the 1960s, China's animation industry saw a big downturn as American and Japanese films <code>flooded</code> into the Chinese market, dominating both domestic television and cinema screens. As a result, Chinese animators <code>increasingly</code> began to work for western studios. However, things changed in 2015 with the release of \"Monkey King: Hero is Back\", a breakthrough for Chinese animation. This film, based on the timeless <code>classic</code> \"Journey to the West\", signaled a new era of creativity and success in the industry. The main character, the Monkey King, is depicted(刻画) as going through a mid-life crisis, which <code>reflects</code> the director's view that cartoons are not just for children.</p><p>Light Chaser Animation, a Beijing-based studio, has contributed to the popularity of cartoons in China. Its production \"30,000 Miles from Chang'an\" <code>combines</code> elements of Chinese culture, history, and legends with aesthetic(美学的) feeling of Tang dynasty poetry. Indeed, traditional themes are widespread among successful Chinese animations, <code>emphasizing</code> the importance of traditional culture as a foundation for Chinese animation. Like other industries, cartoons in China are inspired by Western innovations but with added “Chinese characteristics”.</p>",
        "type": "fishing",
        "distractors": [
            "crafted"
        ],
        "id": "MCP-_"
    },
    {
        "text": "<p>In a bustling city in Arizona stood a high school where most of the students live in poverty. Among them were four sons of Mexican immigrants, Juan, Oscar, Luis, and Alfredo. These boys, coming from <code>humble</code> backgrounds, often found themselves overlooked and underestimated. Bonded by fate and friendship, they shared a common passion for <code>mechanics</code>. Two science teachers there decided to enter their high school into a complicated <code>underwater</code> robotics competition sponsored by the NASA and the Naval Research. Excited for the news, these four boys signed up for the competition.</p><p>With enthusiasm and energy, they started calling mechanical engineers for design help. They were <code>advised</code> that these kinds of robots require glass syntactic flotation foam, a type of floating material used in various marine applications. <code>Short of</code> money, all they could afford was some PVC pipes and duct tape(强力胶布). <code>Therefore</code>, they searched the city for various spare parts, gathering whatever they could to bring their vision to life. With the teachers' guidance and encouragement, they <code>pieced</code> together a robot with no more than metal and wires.</p><p>As they worked on their robot, the boys also faced personal challenges. Juan struggled with the weight of family responsibilities; Oscar <code>battled</code> a deep-seated fear of failure; Luis's heart ached from the constant peers' mockery(嘲笑) for his <code>strange</code> accent, and Alfredo longed for acceptance and belonging. <code>Despite</code> these obstacles, they persevered, leaning on each other for support and inspiration.</p><p>After a few test runs of their robot, they piled into a second-hand van to head to the competition. Upon entering the main pool area, they noticed the college teams wearing matching outfits, with robots sponsored by big companies. Feeling a bit nervous, the boys put the robot in the water for a test run. <code>Unfortunately</code>, the PVC didn't hold up, causing the robot to leak and sink.</p><p>However, instead of letting this <code>failure</code> ruin their spirits, the boys put their heads together and came up with a brilliant solution. 12 hours later, armed with 8 super-absorbent pads to plug the leak, the robot was <code>lowered</code> into the pool again. This time, their robot performed admirably. Gliding gracefully through the waters, it navigated the course with precision and speed, <code>wowing</code> the judges and audience alike. This underwater robot, a symbol of their determination and <code>perseverance</code> conquered the waters, defeated engineering powerhouse MIT and ranked first in the country. This was not just a win for those four but a victory for every underdog with a dream.</p>",
        "type": "cloze",
        "questions": [
            {
                "original": "humble",
                "distractors": [
                    "academic",
                    "relevant",
                    "professional"
                ]
            },
            {
                "original": "mechanics",
                "distractors": [
                    "space",
                    "research",
                    "ocean"
                ]
            },
            {
                "original": "underwater",
                "distractors": [
                    "giant",
                    "industrial",
                    "local"
                ]
            },
            {
                "original": "advised",
                "distractors": [
                    "forced",
                    "challenged",
                    "consulted"
                ]
            },
            {
                "original": "Short of",
                "distractors": [
                    "Reliant on",
                    "Available to",
                    "Desperate for"
                ]
            },
            {
                "original": "Therefore",
                "distractors": [
                    "Otherwise",
                    "Moreover",
                    "However"
                ]
            },
            {
                "original": "pieced",
                "distractors": [
                    "tied",
                    "added",
                    "wrapped"
                ]
            },
            {
                "original": "battled",
                "distractors": [
                    "conquered",
                    "created",
                    "expressed"
                ]
            },
            {
                "original": "strange",
                "distractors": [
                    "perfect",
                    "slight",
                    "elegant"
                ]
            },
            {
                "original": "Despite",
                "distractors": [
                    "With",
                    "Given",
                    "Besides"
                ]
            },
            {
                "original": "Unfortunately",
                "distractors": [
                    "Basically",
                    "Actually",
                    "Consequently"
                ]
            },
            {
                "original": "failure",
                "distractors": [
                    "disagreement",
                    "conflict",
                    "progress"
                ]
            },
            {
                "original": "lowered",
                "distractors": [
                    "sealed",
                    "inserted",
                    "fed"
                ]
            },
            {
                "original": "wowing",
                "distractors": [
                    "boring",
                    "confusing",
                    "motivating"
                ]
            },
            {
                "original": "perseverance",
                "distractors": [
                    "bravery",
                    "generosity",
                    "confidence"
                ]
            }
        ],
        "id": "VMwYk"
    },
    {
        "text": "<h2>(A)</h2><p>Among my oldest friends, I'm known as the mysterious one, the guy who rarely shows up, is always there not here. I had high school buddies, and I loved them all dearly though we boys didn't say such things back then. Then life happened. Most of us left our hometown. Meet-ups become rare occasions.</p><p>One of those old friends, whom I had not seen since our high school graduation, reached out recently to say he'd be near where I am, and hoped we could meet up. He'd done the same thing about 10 years ago, and I'd begged off for some stupid reason related to my shyness, or rather, my introverted nature. I'm older and a bit wiser now, and I've been packing around some guilt over that missed opportunity for 10 years, so I agreed readily.</p><p>We met for dinner, perhaps two hours, and rarely had I felt at ease with other humans as I did with him. We talked and talked. About who we were then. Who we are now. And what made us the jerks(混蛋) we were then. We acknowledged that if not for each other, and the circles of good people we ran with back then, the good friends who kept us reasonably on track and in check, life could have easily gone south for either of us. Each of us recalled things the other had no memory of. Fragments of memories, scattered yet precious. We know we were tight then, and we value that friendship and shared experience still today.</p><p>People are fundamentally social beings and enjoy connecting with others. Maintaining social connections is good for our mental and physical health. However, despite the importance and enjoyment of social connection, people significantly underestimate how much others will appreciate being reached out to.</p><p>There's something about the friends you make in youth that's near impossible to recreate with friends you make later in life. I'm telling you this to remind you that your old friends would love to hear from you, maybe a simple text, a little hello, maybe even a phone call or a meetup.</p>",
        "type": "reading",
        "questions": [
            {
                "q": "The author refused the meet-up about 10 years ago probably because __________.",
                "a": [
                    "he was not a sociable man.",
                    "he was not clever enough.",
                    "he lived far away from his friends.",
                    "he felt guilty about his friends."
                ],
                "correct": 0
            },
            {
                "q": "Which of the following best describes the author's feeling during the dinner?",
                "a": [
                    "Anxious and nervous.",
                    "Comfortable and relaxed.",
                    "Excited and energetic.",
                    "Sad and regretful."
                ],
                "correct": 1
            },
            {
                "q": "What does the author imply by saying \"life could have easily gone south for either of us\"?",
                "a": [
                    "They could have easily been off the track in life.",
                    "They might have settled down in the southern region.",
                    "Their friendship could have easily turned sour.",
                    "They could have faced financial difficulties."
                ],
                "correct": 0
            },
            {
                "q": "What is the main purpose of the article?",
                "a": [
                    "To describe the author's reunion with an old friend.",
                    "To reflect on the value of friendships formed in youth.",
                    "To encourage readers to reach out to their old friends.",
                    "To discuss the importance of social connections."
                ],
                "correct": 2
            }
        ],
        "id": "4mdZf"
    },
    {
        "text": "<h2>(B)</h2><p><h2>WORLD 2024</h2><p><h3>Run Like Olympians</h3><p>WHERE Paris, France WHEN AUGUST</p><p>For the first time, members of the public will be able to run their own marathon during the 2024 Summer Olympics, just one initiative aimed at creating a more inclusive Games. Held in the evening between the men's and women's official races, the Marathon Games will allow 20,024 qualifying lottery(彩票) winners on the 26-mile route that links Paris and Versailles.</p><p><h3>Hear It Live</h3><p>WHERE Kyoto, Japan WHEN YEAR-ROUND</p><p>Guidebooks speak of Kyoto as frozen in time, with quiet temples and peaceful gardens. But after hours, Japan's ancient capital reveals a live music scene. Rock, swing, and even Irish music echo into the night. Whatever you're into, from jazz to punk, there's a community for you to share. \"This is what happens in Japan when the mask comes off,\" says Kyoto guide Van Milton.</p><p><h3>Ski New Peaks</h3><p>WHERE Georgia WHEN DEC-APR</p><p>Long as a means of transportation, hunting and exploration, skiing is still a way of life in the mountainous republic of Georgia. Now visitors can enjoy some of the nation's best back-country skiing in the Caucasus. In Svaneti, journeys may lead skiers through Gvibari Pass or to Ushguli village.</p><p><h3>Explore Ancient Art</h3><p>WHERE Algeria WHEN OCT-NOV</p><p>Algeria is home to Africa's largest national park, which holds one of the world's greatest concentrations of ancient rock art. Tassilin'Ajjer National Park is a geologic wonderland, but these rock forests are only half the story. Neolithic(新石器时代的) hunter-gatherers left 15,000 rock carvings here, including images of elephants and giraffes. These animals are more commonly associated with sub-Saharan Africa a hint that this deserted wilderness was once a fertile grassland.</p>",
        "type": "reading",
        "questions": [
            {
                "q": "As a student who is fond of sports, where is Jane most likely to visit during the summer vacation?",
                "a": [
                    "Georgia",
                    "Kyoto",
                    "Algeria",
                    "Paris"
                ],
                "correct": 3
            },
            {
                "q": "What can we infer from the passage?",
                "a": [
                    "Everyone can enter for the Marathon Games in the summer of 2024.",
                    "Kyoto features the peaceful daytime and energetic nightlife.",
                    "Visitors worldwide can enjoy skiing in Georgia all year round.",
                    "Rock carvings in Algeria were created by artists to attract tourists."
                ],
                "correct": 1
            },
            {
                "q": "What is the main idea of the passage?",
                "a": [
                    "It presents attractions in different regions of the world.",
                    "It shows the beauty of rural landscapes around the world.",
                    "It lists the most popular places of interest in the world.",
                    "It discovers the hidden treasures in western cultures."
                ],
                "correct": 0
            }
        ],
        "id": "KSi2k"
    },
    {
        "text": "<h2>(C)</h2><p>With its bright colors, easy-to-learn rules and familiar music, the video game Tetris has endured as a pop culture symbol over the past 40 years. Many people, like me, have been playing the game for decades, and it has been updated to adapt to new technologies like game systems, phones and tablets.</p><p>However, Tetris is much more than winning. The game, in which players must control blocks of different shapes as they slide down a screen, is based on a fundamental element of geometry, called dynamic spatial reasoning(动态空间推理). It is taught by mathematics educators and used by architects, engineers, animators, and many others. Players employ these geometric skills to progress in Tetris, so playing it both tests and improves a player's dynamic spatial reasoning.</p><p>Spatial reasoning is the ability to visualize geometric figures and how they will move in space. So, dynamic spatial reasoning is the ability to visualize actively moving figures. The Tetris player must quickly decide where the falling game piece will best fit and then move it there. This movement involves both translation — moving a shape right and left, and rotation — turning its shape by 90 degrees at a time.</p><p>Spatial visualization is a key element of a mathematics discipline called transformational geometry, which is usually first taught in middle school. In a typical transformational geometry exercise, students might be asked to represent a figure by its x and y coordinates(坐标) on a coordinate graph and then identify the transformations, such as translation and rotations, necessary to move it from one position to another while keeping the piece the same shape and size.</p><p>While it may seem simple, transformational geometry is the foundation for several advanced topics in mathematics. Architects and engineers both use transformations to draw up blueprints, which represent the real world in scale drawings. Animators use concepts of transformations as well. While animators today use computer programs that automatically move figures around, they are all based on this kind of transformation.</p>",
        "type": "reading",
        "questions": [
            {
                "q": "Which is NOT a key reason for Tetris's lasting popularity?",
                "a": [
                    "Its pleasure of winning the game.",
                    "Its bright colors and catchy music.",
                    "Its link to complex math and geometry.",
                    "Its simple rules and tech adaptability."
                ],
                "correct": 2
            },
            {
                "q": "According to the passage, what fundamental skill does playing Tetris help improve?",
                "a": [
                    "Logical reasoning.",
                    "Mathematical calculation.",
                    "Memory maintaining.",
                    "Spatial visualization."
                ],
                "correct": 3
            },
            {
                "q": "Move the sample block on the right using both translation and rotation. Which image below can we get?",
                "a": [
                    "(a)",
                    "(b)",
                    "(c)",
                    "(d)"
                ],
                "correct": 2
            },
            {
                "q": "Which of the following statements does the author most probably agree with?",
                "a": [
                    "Tetris is a particularly useful tool for animation and architecture designs.",
                    "Spatial visualization is based on the constant change of a figure's position.",
                    "Transformational geometry behind Tetris can be applied to various fields.",
                    "Spatial reasoning is too difficult for middle school students to master."
                ],
                "correct": 2
            }
        ],
        "id": "Wxlm3"
    },
    {
        "text": "<h2>Rain Collection</h2><p>What do you like to do on a rainy day — sit inside and listen to the pitter-patter on the roof or splash outside and feel the cold drops on your face? Whatever you choose, rain is vitally essential in the nature.</p><p><code>We all deeply depend on the nourishment of rain.</code> It fills rivers and lakes, slowly sinks into the earth, nourishes our plants, and keeps the land alive and beautiful. In the past, people obtained their water from rain, wells, or nearby rivers. Now, many of us live in places where water is piped in, sometimes from far away. Removing so much water from nature and sending it to great distances harm the living things that also need that water.</p><p>As climate change heats up the planet and causes extreme weather, more places face water shortages. <code>To secure future water supply, we need new sources.</code> One easy place to look for more water is the sky!</p><p>Humans have collected rain since ancient times. <code>Now, many people are returning to this practice.</code> They are tapping into this clean and rich source of water provided by nature. By harvesting the rain we can reduce the amount of water we take from rivers and out of the ground.</p><p>Even in dry climates, there is a lot of potential rainwater that can be effectively harvested and utilized. This rich yet often overlooked resource has the potential to significantly contribute to water conservation efforts, especially in regions facing water shortages. Just one inch of rain falling on a medium-sized house produces over 600 gallons of water. <code>Large roofs can, hence, collect greater amount of water.</code></p><p>Nowadays, rainwater is still used as a primary supply in many places in the world, like Vietnam and Hawaii. In places with piped-in water, rainwater is not commonly used, but this is changing. Rainwater harvesting is getting more popular since it's easy to do and helps create water security.</p>",
        "type": "sentences",
        "distractors": [
            "Rainwater can also be used for fountains and ponds.",
            "Rainwater is clean but it gets dirty from the roof."
        ],
        "id": "vtnU7"
    }
])

export const MOCK_ANSWERS = {
    '1': 'when',
    '2': 'where',
    '3': 'could',
    '4': 'What',
    '5': 'to seek',
    '6': 'instead of',
    '7': 'was published',
    '8': 'hugged',
    '9': 'more appealing',
    '10': 'performing',
    '11': 'D',
    '12': 'I',
    '13': 'K',
    '14': 'F',
    '15': 'C',
    '16': 'B',
    '17': 'G',
    '18': 'E',
    '19': 'H',
    '20': 'J',
    '21': 'D',
    '22': 'C',
    '23': 'C',
    '24': 'D',
    '25': 'A',
    '26': 'A',
    '27': 'B',
    '28': 'C',
    '29': 'C',
    '30': 'C',
    '31': 'D',
    '32': 'A',
    '33': 'A',
    '34': 'A',
    '35': 'D',
    '36': 'A',
    '37': 'B',
    '38': 'A',
    '39': 'B',
    '40': 'D',
    '41': 'B',
    '42': 'A',
    '43': 'C',
    '44': 'D',
    '45': 'D',
    '46': 'C',
    '47': 'F',
    '48': 'A',
    '49': 'D',
    '50': 'E'
} as const

export const MOCK_ANSWERS_AGGR = [
    // Variation 1
    [
        "while",
        "wherever",
        "could",
        "What",
        "to seek",
        "rather than",
        "was published",
        "hugging",
        "more attractive",
        "performs",
        "D",
        "I",
        "K",
        "F",
        "C",
        "A",
        "G",
        "E",
        "H",
        "J",
        "A",
        "D",
        "C",
        "B",
        "A",
        "A",
        "B",
        "C",
        "D",
        "C",
        "D",
        "B",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "C",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 2
    [
        "when",
        "where",
        "can",
        "Which",
        "seeking",
        "instead of",
        "was published",
        "hugged",
        "more appealing",
        "performed",
        "C",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "B",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "C",
        "B",
        "B",
        "A",
        "B",
        "D",
        "A",
        "A",
        "C",
        "D",
        "D",
        "C",
        "G",
        "A",
        "D",
        "E",
    ],
    // Variation 3
    [
        "whenever",
        "where",
        "could",
        "What",
        "to seek",
        "in place of",
        "got published",
        "hugged",
        "more appealing",
        "performing",
        "D",
        "J",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "D",
        "C",
        "A",
        "B",
        "F",
        "B",
        "C",
        "E",
    ],
    // Variation 4
    [
        "when",
        "wherever",
        "could",
        "What",
        "to seek",
        "instead of",
        "was published",
        "hugged",
        "more attractive",
        "performing",
        "D",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "G",
        "A",
        "D",
        "H",
    ],
    // Variation 5
    [
        "while",
        "where",
        "can",
        "What",
        "seeking",
        "rather than",
        "was published",
        "hugged",
        "more appealing",
        "performs",
        "D",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 6
    [
        "when",
        "where",
        "could",
        "Which",
        "to seek",
        "instead of",
        "got published",
        "hugged",
        "more appealing",
        "performing",
        "C",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "I",
    ],
    // Variation 7
    [
        "whenever",
        "where",
        "could",
        "What",
        "to seek",
        "in place of",
        "was published",
        "hugged",
        "more attractive",
        "performed",
        "D",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 8
    [
        "when",
        "wherever",
        "can",
        "What",
        "seeking",
        "instead of",
        "was published",
        "hugged",
        "more appealing",
        "performs",
        "D",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 9
    [
        "while",
        "where",
        "could",
        "Which",
        "to seek",
        "rather than",
        "got published",
        "hugged",
        "more appealing",
        "performing",
        "D",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 10
    [
        "when",
        "where",
        "could",
        "What",
        "to seek",
        "instead of",
        "was published",
        "hugged",
        "more attractive",
        "performed",
        "D",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 11
    [
        "whenever",
        "wherever",
        "could",
        "What",
        "seeking",
        "instead of",
        "was published",
        "hugged",
        "more appealing",
        "performing",
        "A",
        "J",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 12
    [
        "when",
        "where",
        "can",
        "Which",
        "to seek",
        "in place of",
        "was published",
        "hugged",
        "more attractive",
        "performs",
        "D",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 13
    [
        "while",
        "where",
        "could",
        "What",
        "to seek",
        "rather than",
        "got published",
        "hugged",
        "more appealing",
        "performed",
        "D",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 14
    [
        "when",
        "wherever",
        "could",
        "What",
        "seeking",
        "instead of",
        "was published",
        "hugged",
        "more appealing",
        "performing",
        "B",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 15
    [
        "whenever",
        "where",
        "can",
        "Which",
        "to seek",
        "instead of",
        "was published",
        "hugged",
        "more attractive",
        "performing",
        "D",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 16
    [
        "when",
        "where",
        "could",
        "What",
        "to seek",
        "in place of",
        "got published",
        "hugged",
        "more appealing",
        "performs",
        "D",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 17
    [
        "while",
        "wherever",
        "could",
        "What",
        "seeking",
        "rather than",
        "was published",
        "hugged",
        "more appealing",
        "performed",
        "D",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 18
    [
        "when",
        "where",
        "could",
        "Which",
        "to seek",
        "instead of",
        "was published",
        "hugged",
        "more attractive",
        "performing",
        "C",
        "I",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "F",
        "A",
        "D",
        "E",
    ],
    // Variation 19
    [
        "whenever",
        "where",
        "can",
        "What",
        "to seek",
        "instead of",
        "got published",
        "hugs",
        "more appealing",
        "performs",
        "D",
        "J",
        "K",
        "F",
        "C",
        "B",
        "G",
        "E",
        "H",
        "J",
        "D",
        "C",
        "C",
        "D",
        "A",
        "A",
        "B",
        "C",
        "C",
        "C",
        "D",
        "A",
        "A",
        "A",
        "D",
        "A",
        "B",
        "A",
        "B",
        "D",
        "B",
        "A",
        "C",
        "D",
        "D",
        "C",
        "H",
        "A",
        "D",
        "E",
    ],
].map(variation => {
    const obj = {} as Record<string, string>
    variation.forEach((ans, idx) => obj[(idx + 1).toString()] = ans)
    return obj
})
