export const NOT_LISTED_PROMPT = `
你将看到一段外语文本。首先，你需要推断出语言类型。然后，你要为一个这一门语言的学习者尽可能多地挑选其中的词汇和词组搭配添加以下注解：原文形式（必加），屈折变化的原形（必须与原文同词性；若不是专有名词则首字母小写）（是屈折变化的原形而不是构词的原形，例如deployments的原形是deployment而非deploy）（必加），原形的精简语境释义（必加，附带\`\`包裹的音标，该单词有固定搭配时须附带并用*()*包裹），对记忆有助益的语源（同语根词加上时必加），同语根词（选加，选取含有同源词素的不同单词）。尽量详尽地挑选并注解；多多注解外刊中的有价值单词、对英语学习实用的语汇和专有名词（如the Revolution）；禁止反复注解同一词汇；禁止注解初级词汇；必加语源。输出格式为 {{原文形式||原形||释义||(语源解释) 各个语素||语根1 (原意) → 同语根词1, 同语根词2; 语根2 (原意) → 同语根词1; …}}。词性、词义和词源注解的对象必须为屈折变化的原形，例如如果原文为implications，原形为implication，则应按照implication而非imply进行注解，词性为名词，语源中不要加入单复数变化词尾-s；例如如果原文为dazzling，原形为dazzling，则应按照dazzling而非dazzle进行注解，词性为形容词；例如如果原文为forgiven，原形为forgive，则应按照forgive而非forgiven进行注解，词性为动词。

除此以外，不要修改文本其他部分的Markdown语法。直接输出注解后的文章。不要删除紧跟的标点。注解的同源词板块中，同源的语素才是应当加粗的部分（如对于ensue中的sue应加粗pursue中的sue，即“***sue*** (follow) → pur**sue** (追求)”）。注意：同源词素必须来自同一印欧语根；拼写相同的词素未必同源（例如sur**veill**ance的同源词不是veil（面纱），而是vigilant（watchful），因此语源为“意即从上观察: ***sur*** (above) + ***veil*** (watch) + ***-ance*** (forming n., 表行为)”，同源词为“***veil*** → **vigil**ance (警觉)”），同源词素也不必拼写相同（例如break和fragile）。不必把词尾的非词缀语素强行放入语源。必须注解词汇在语境中的具体含义，若为比喻义、引申义则须指出。第二格中给出的原形是第三格的注解对象，例如若原形为obsessed，则释义为形容词；若原形为obsess，则释义为动词。必要时在释义中附带用法，如对inferior附带*(be inferior to)*，对devote（献身意时）附带*(devote oneself to something)*，对appeal附带*(appeal to someone)*，但原文中没有用法时无需注解；固定搭配则放入例句。
 
以下是几个对于英语的示例。请参考这些示例，并根据其格式为其他语言的文本添加注解。

示例文本一：
Birds, nowadays, all live in imperilled mansions. I <must>studied up</must> on birds that are famously difficult to identify so that when I first saw them in the field, I had an inkling of what they were without having to check a field guide. I used the many tools now available to novices: EBird shows where other birders go and reveals how different species navigate space and time; Merlin is best known as an identification app but is secretly an incredible encyclopedia; Birding Quiz lets you practice identifying species based on fleeting glances at bad angles.

示例输出一：
Birds, nowadays, all live in {{imperilled||imperil||**v. 危及** \`ɪmˈpɛrɪl\` put (someone or something) at risk||意即“使陷入危险”: ***im-*** (into, forming v.) + ***per*** (try, risk) + ***-il***||***peril*** (danger) → **peril**ous (危险的); ***per*** (try, risk) → ex**pir**ical (经验的)}} {{mansions||mansion||**n. 大厦** \`ˈmænʃən\` a large and imposing house||原意“居住之地”: ***man-*** (stay) + ***-sion*** (forming n., 表状态) ||***man-*** (stay) → re**main** (不变), **main**tain (维系)}}. I {{studied up on||study up on||**phr. 调查** learn intensive about}} birds that are famously difficult to identify so that when I first saw them in the field, I had an {{inkling||inkling||**n. 略知** \`ˈɪŋklɪŋ\` *(have an inkling of)* a slight knowledge}} of what they were without having to check a field guide. I used the many tools now available to novices: EBird shows where other birders go and {{reveals||reveal||**v. 揭示** \`rᵻˈviːl\` make known||语源“揭开面纱”: ***re-*** (expressing reversal, 表反义) + ***veal*** (veil, 面纱)}} how different species navigate space and time; Merlin is best known as an identification app but is secretly an incredible {{encyclopaedia||encyclopaedia||**n. 百科全书** \`ᵻnˌsʌɪklə(ʊ)ˈpiːdɪə\` a book giving various information||“周全、并包的教育”意: ***en-*** (inside) + ***cyclo*** (circle) + ***paedia*** (education)||***paedia*** (child) → **paedia**tric (儿科的)}}; Birding Quiz lets you practice identifying species based on fleeting glances at bad angles.

示例文本二：
It transpires that many petrified people are lunatics. Of course, living with uncertainty and risk is nothing new. How should mortal creatures who have spent our long evolution struggling to survive feel but insecure? The precarious and unpredictable nature of life is what helped inspire the ancient Stoics to <must>counsel</must> equanimity and Buddhist thinkers to develop the concept of Zen. A kind of existential insecurity is indelible to being human.

示例输出二：
It {{transpires||transpire||**v. 被表明是** \`trænˈspaɪə\` happen; become known||原形容水汽“升腾”: ***trans-*** (across) + ***spire*** (breathe) ||***trans-*** (across) → **trans**fer (转移), **trans**late (翻译); ***spire*** (breathe) → in**spire** (吹入灵感, 鼓舞)}} that many {{petrified||petrify||**v. 惊呆** \`ˈpɛtrɪfaɪ\` *(be petrified by)* make (someone) so frightened that they are unable to move or think||意为“石化”: ***petr-*** (stone) + ***-ify*** (forming v., ……化, 表状态改变)||***petr-*** (stone) → **petr**oleum (石油)}} people are {{lunatics||lunatic||**n. 疯子** \`ˈluːnətɪk\` a person who is mentally ill, especially one exhibiting irrational or dangerous behavior||来自“月相使人颠狂”的观念: ***lun-*** (moon) + ***-atic*** (forming adj., 表状态) ||***lun-*** (moon) → **lun**ar (月球的)}}. Of course, living with uncertainty and risk is nothing new. How should mortal creatures who have spent our long evolution struggling to survive feel but insecure? The {{precarious||precarious||**adj. 不稳固的** \`prɪˈkeriəs\` not securely held||“艰难求来的”意: ***prec*** (entreaty, 求得) + ***-ous*** (forming adj.)||***prec*** (entreaty, 恳求) → **pray**er (祈祷)}} and unpredictable nature of life is what helped inspire the ancient Stoics to {{counsel||counsel||**v. 建议** \`ˈkaʊnsl\` recommend (a course of action)}} equanimity and Buddhist thinkers to develop the concept of Zen. A kind of existential insecurity is {{indelible||indelible||**adj. 不可消弭的** \`ɪnˈdɛlɪb(ə)l\` not able to be removed||语源“不能够删去的”: ***in-*** (not) + ***del*** (delete) + ***-ible*** (forming adj.)}} to being human.
`.trim()
