'use client'

import Image from 'next/image'
import { ENGLISH_MODERN } from '@/lib/fonts'
import { cn } from '@/lib/utils'
import Markdown from '../markdown'
import { Accordion, AccordionItem } from '@heroui/react'

export default function TimesPanel() {
    const dates = [
        { date: '14', month: 'Dec', painting: 'https://pcsjszvydprmevipvpva.supabase.co/storage/v1/object/public/app-assets/times/example/Cable%20Car.webp' },
        { date: '13', month: 'Dec', painting: 'https://pcsjszvydprmevipvpva.supabase.co/storage/v1/object/public/app-assets/times/example/Launch%20Station.webp' },
        { date: '12', month: 'Dec', painting: 'https://pcsjszvydprmevipvpva.supabase.co/storage/v1/object/public/app-assets/times/example/Oil%20Rig.webp' },
        { date: '11', month: 'Dec', painting: 'https://pcsjszvydprmevipvpva.supabase.co/storage/v1/object/public/app-assets/times/example/Pirate%20Lookout.webp' },
    ]

    return (
        <div className={cn('h-dvh w-dvw p-4', ENGLISH_MODERN.className)}>
            {/* Main Paper Container */}
            <div className='w-full h-full flex flex-col md:flex-row bg-white rounded-3xl'>
                <div className='flex md:h-full md:min-w-60 md:flex-col md:overflow-y-auto overflow-x-auto'>
                    {/* Sidebar */}
                    <div className='flex flex-row md:flex-col md:static inset-y-0 left-0 z-40 bg-white'>
                        <div className='p-6'>
                            <div className='flex flex-row md:flex-col space-x-4 md:space-x-0 md:space-y-3'>
                                {dates.map((item, index) => (
                                    <div
                                        key={index}
                                        className='relative flex-shrink-0 w-40 md:w-full h-20 md:h-auto aspect-square cursor-pointer hover:scale-105 transition-transform duration-200 rounded-2xl overflow-hidden group'
                                    >
                                        <Image
                                            src={item.painting}
                                            alt='Date background'
                                            fill
                                            sizes='400px'
                                            className='absolute object-cover opacity-90 group-hover:opacity-100 transition-opacity'
                                        />
                                        <div className='absolute inset-0 bg-black/20' />
                                        <div className='absolute inset-0 flex flex-col items-center justify-center text-white'>
                                            <div className='text-4xl'>{item.date}</div>
                                            <div className='text-lg opacity-90'>{item.month}</div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>

                <div className='flex h-full overflow-y-auto overflow-x-hidden'>
                    {/* Main Content */}
                    <article className='m-6 md:px-4 md:my-12 prose-lg prose'>
                        {/* Header */}
                        <div>
                            <h1 className='mb-2 font-semibold'>December 14, 2024</h1>
                            <span className='text-xl opacity-80'>Brought to you with AI by The Leximory Times</span>
                        </div>

                        {/* Cover Image */}
                        <div className='relative w-full aspect-video rounded-2xl overflow-hidden mb-5'>
                            <Image src='https://pcsjszvydprmevipvpva.supabase.co/storage/v1/object/public/app-assets/times/example/Cable%20Car.webp' alt='Daily cover' fill sizes='600px' className='object-cover object-center rounded-2xl' />
                        </div>
                        <Accordion>
                            <AccordionItem title='Daily Novel: The Great Gatsby' classNames={{
                                base: 'not-prose -mb-4',
                                title: 'text-xl',
                            }}>
                                <Markdown
                                    className='prose-lg'
                                    fontFamily={ENGLISH_MODERN.style.fontFamily}
                                    md={`
                         In her {{memoir||memoir||**n. 回忆录** \`ˈmɛmwɑr\` a historical account or biography written from personal knowledge or special sources||源自拉丁语，意为“记忆”：***memor*** (mindful, 记得) + ***-ia*** (forming n., 表状态)||***memor*** (mindful, 记得) → **memor**y (记忆), com**memor**ate (纪念)}}, Dorothy Allison writes, “Two or three things I know for sure and one of them is that telling the story all the way through is an act of love.”

Throughout my teaching career at independent schools, which began during the Clinton administration, I’ve also been telling students that reading a story all the way through is an act of love. It takes stillness and {{receptivity||receptivity||**n. 接受能力** \`ˌrɛsɛpˈtɪvɪti\` willingness to consider or accept new ideas||语源“接受的状态”: ***recept*** (receive) + ***-ivity*** (forming n., 表性质)||***recept*** (receive) → **recept**ion (接待), **recept**acle (容器)}} to realize this, it takes a willingness to enter the life of someone you’ll never meet, and it requires great practice.

It’s easy to join the hand-wringing chorus, blaming TikTok’s corn drill challenge, Jake Paul and their {{ilk||ilk||**n. 类型** \`ɪlk\` a type of people or things similar to those already referred to||源自古英语，意为“相同”：***ilca*** (same)}} for the {{diminuendo||diminuendo||**n. 渐弱** \`dɪˌmɪnjuˈɛndoʊ\` a decrease in loudness in music||源自意大利语，意为“逐渐减少”：***di-*** (away) + ***minuere*** (to diminish)||***minuere*** (to diminish) → **minu**te (微小的)}} of Dickens. But we cannot let reading become another {{bygone||bygone||**adj. 过去的** \`ˈbaɪɡɔn\` belonging to an earlier time||语源“被……走了的”：***by-*** (past) + ***gone*** (gone)}} practice. In their more than eight hours of screen time a day, on average, students navigate a {{galaxy||galaxy||**n. 大量** \`ˈɡæləksi\` a system of millions or billions of stars, together with gas and dust, held together by gravitational attraction||源自希腊语，意为“银河”：***galaxias*** (milky)}} of {{mediated||mediate||**adj. 间接的** \`ˈmiːdieɪt\` *(mediated by)* influenced by||语源“居于中间”：***medi-*** (middle) + ***-ate*** (forming adj., 表状态)||***medi-*** (middle) → **medi**um (媒介), **medi**an (中间值)}} experiences; schools need to be a {{bastion||bastion||**n. 堡垒** \`ˈbæstiən\` an institution, place, or person strongly defending or upholding particular principles, attitudes, or activities||源自意大利语，意为“防御工事”：***bastire*** (to build)}} of the analog experience of the physical book.

The study of English involves more than reading. It includes written expression and the {{cultivation||cultivation||**n. 培养** \`ˌkʌltɪˈveɪʃən\` the action of cultivating land, or the state of being cultivated||语源“耕种”：***cult-*** (till) + ***-ivation*** (forming n., 表行为)||***cult-*** (till) → **cult**ure (文化), agri**cult**ure (农业)}} of an authentic voice. But the comprehension of literature, on which the study of English is based, is rooted in the pleasure of reading. Sometimes there will be a beam of light that falls on a room of
                                    `}
                                />
                            </AccordionItem>
                        </Accordion>

                        <h3>Daily News</h3>
                        {/* Content */}
                        <Markdown
                            className='prose-lg pb-10'
                            fontFamily={ENGLISH_MODERN.style.fontFamily}
                            md={`
                         In her {{memoir||memoir||**n. 回忆录** \`ˈmɛmwɑr\` a historical account or biography written from personal knowledge or special sources||源自拉丁语，意为“记忆”：***memor*** (mindful, 记得) + ***-ia*** (forming n., 表状态)||***memor*** (mindful, 记得) → **memor**y (记忆), com**memor**ate (纪念)}}, Dorothy Allison writes, “Two or three things I know for sure and one of them is that telling the story all the way through is an act of love.”

Throughout my teaching career at independent schools, which began during the Clinton administration, I’ve also been telling students that reading a story all the way through is an act of love. It takes stillness and {{receptivity||receptivity||**n. 接受能力** \`ˌrɛsɛpˈtɪvɪti\` willingness to consider or accept new ideas||语源“接受的状态”: ***recept*** (receive) + ***-ivity*** (forming n., 表性质)||***recept*** (receive) → **recept**ion (接待), **recept**acle (容器)}} to realize this, it takes a willingness to enter the life of someone you’ll never meet, and it requires great practice.

It’s easy to join the hand-wringing chorus, blaming TikTok’s corn drill challenge, Jake Paul and their {{ilk||ilk||**n. 类型** \`ɪlk\` a type of people or things similar to those already referred to||源自古英语，意为“相同”：***ilca*** (same)}} for the {{diminuendo||diminuendo||**n. 渐弱** \`dɪˌmɪnjuˈɛndoʊ\` a decrease in loudness in music||源自意大利语，意为“逐渐减少”：***di-*** (away) + ***minuere*** (to diminish)||***minuere*** (to diminish) → **minu**te (微小的)}} of Dickens. But we cannot let reading become another {{bygone||bygone||**adj. 过去的** \`ˈbaɪɡɔn\` belonging to an earlier time||语源“被……走了的”：***by-*** (past) + ***gone*** (gone)}} practice. In their more than eight hours of screen time a day, on average, students navigate a {{galaxy||galaxy||**n. 大量** \`ˈɡæləksi\` a system of millions or billions of stars, together with gas and dust, held together by gravitational attraction||源自希腊语，意为“银河”：***galaxias*** (milky)}} of {{mediated||mediate||**adj. 间接的** \`ˈmiːdieɪt\` *(mediated by)* influenced by||语源“居于中间”：***medi-*** (middle) + ***-ate*** (forming adj., 表状态)||***medi-*** (middle) → **medi**um (媒介), **medi**an (中间值)}} experiences; schools need to be a {{bastion||bastion||**n. 堡垒** \`ˈbæstiən\` an institution, place, or person strongly defending or upholding particular principles, attitudes, or activities||源自意大利语，意为“防御工事”：***bastire*** (to build)}} of the analog experience of the physical book.

The study of English involves more than reading. It includes written expression and the {{cultivation||cultivation||**n. 培养** \`ˌkʌltɪˈveɪʃən\` the action of cultivating land, or the state of being cultivated||语源“耕种”：***cult-*** (till) + ***-ivation*** (forming n., 表行为)||***cult-*** (till) → **cult**ure (文化), agri**cult**ure (农业)}} of an authentic voice. But the comprehension of literature, on which the study of English is based, is rooted in the pleasure of reading. Sometimes there will be a beam of light that falls on a room of students collectively leaning into a story, with only the {{scuffing||scuff||**adj. 拖着脚走的** \`skʌf\` scrape or brush the surface of (something) against something else||拟声词，模仿摩擦的声音}} sounds of pages, and it’s as though all our heartbeats have slowed. But we have introduced so many {{antagonists||antagonist||**n. 对立因素** \`ænˈtæɡənɪst\` a person who actively opposes or is hostile to someone or something; an adversary||语源“对抗者”：***anti-*** (against) + ***agon*** (struggle) + ***-ist*** (forming n., 表人)||***anti-*** (against) → **anti**dote (解药), **anti**pathy (反感); ***agon*** (struggle) → **agon**y (痛苦), **agon**ize (苦恼)}} to scrape against this stillness that reading seems to be impractical.

The test scores released at the end of last month by the National Assessment of Educational Progress reveal {{disturbing||disturbing||**adj. 令人不安的** \`dɪˈstɜːrbɪŋ\` causing anxiety; worrying||语源“扰乱的”：***dis-*** (expressing reversal, 表否定) + ***turb*** (disturb) + ***-ing*** (forming adj., 表性质)||***turb*** (disturb) → **turb**ulence (动荡), per**turb** (扰乱)}} trend lines for the future of literacy in our country. Thirty-three percent of eighth graders scored “below basic” on reading skills, meaning they were unable to determine the main idea of a text or identify differing sides of an argument. This was the worst result in the exam’s 32-year history. To make matters worse, or perhaps to explain how we got here, the assessment reported that in 2023 only 14 percent of students said they read for fun almost every day, a drop of 13 percentage points since 2012.

In its attempt to make English more relevant, the National Council of Teachers of English — devoted to the improvement of language arts instruction — announced in 2022 that it would widen its doors to the digital and mediated world. The aim was to retreat from the {{primacy||primacy||**n. 首要地位** \`ˈpraɪməsi\` the state of being first or most important||语源“第一的状态”：***prim-*** (first) + ***-acy*** (forming n., 表状态)||***prim-*** (first) → **prim**e (首要的), **prim**ary (主要的)}} of the written word and invite more ideas to be represented by images and multimedia. “It {{behooves||behoove||**v. 理应** \`bɪˈhuːv\` be appropriate or necessary||源自古英语，意为“有益”：***be-*** (intensive, 加强) + ***hof*** (advantage)}} our profession, as {{stewards||steward||**n. 管家** \`ˈstuːərd\` a person employed to manage another's property, especially on a large estate||源自古英语，意为“房屋的看守者”：***stig*** (hall) + ***weard*** (guard)}} of the communication arts, to confront and challenge the {{tacit||tacit||**adj. 默许的** \`ˈtæsɪt\` understood or implied without being stated||源自拉丁语，意为“沉默的”：***tacere*** (to be silent)}} and {{implicit||implicit||**adj. 含蓄的** \`ɪmˈplɪsɪt\` implied though not plainly expressed||语源“包含在内的”：***im-*** (in) + ***plic*** (fold) + ***-it*** (forming adj., 表性质)||***plic*** (fold) → **plic**ate (褶皱), com**plic**ate (使复杂)}} ways in which print media is {{valorized||valorize||**v. 提升价值** \`ˈvæləraɪz\` give or ascribe value or validity to (something)||语源“赋予价值”：***valor*** (value) + ***-ize*** (forming v., ……化)||***valor*** (value) → **val**ue (价值), **val**iant (英勇的)}} above the full range of literacy {{competencies||competency||**n. 能力** \`ˈkɑːmpɪtənsi\` the ability to do something successfully or efficiently||语源“胜任的状态”：***com-*** (together) + ***pet*** (seek) + ***-ency*** (forming n., 表状态)||***pet*** (seek) → com**pet**e (竞争), re**peat** (重复)}} students should master,” the council said.

Around the time this decision was made, only 37 percent of American 12th graders were rated as {{proficient||proficient||**adj. 熟练的** \`prəˈfɪʃənt\` competent or skilled in doing or using something||语源“精通的”：***pro-*** (forward) + ***fac*** (do) + ***-ient*** (forming adj., 表性质)||***fac*** (do) → **fac**t (事实), **fac**ile (容易的)}} or better at reading. So the council’s determination that “the time has come to {{decenter||decenter||**v. 转移中心** \`diːˈsɛntər\` move (something) away from the center||语源“从中心移开”：***de-*** (away) + ***center*** (center)}} book reading and essay writing as the {{pinnacles||pinnacle||**n. 顶峰** \`ˈpɪnək(ə)l\` the most successful point; the culmination||源自拉丁语，意为“小尖顶”：***pinna*** (feather, wing)}} of English language arts education” seems highly {{questionable||questionable||**adj. 可疑的** \`ˈkwɛstʃənəbl\` open to doubt or debate||语源“值得疑问的”：***question*** (question) + ***-able*** (forming adj., 表可能)||***question*** (疑问) → in**quest** (调查), re**quest** (请求)}}.


But {{literacy||literacy||**n. 读写能力** \`ˈlɪtərəsi\` the ability to read and write||语源“识字”: ***liter*** (letter) + ***-acy*** (forming n., 表性质)||***liter*** (letter) → **letter** (信), **liter**ature (文学)}} involves more than the {{scraps||scrap||**n. 碎片** \`skræp\` a small piece or amount of something, especially one that is left over after the greater part has been used}} and {{fragments||fragment||**n. 碎片** \`ˈfræɡmənt\` a small part broken or separated off something||语源“打破”: ***frag*** (break) + ***-ment*** (forming n., 表状态)||***frag*** (break) → **frag**ile (易碎的), **frag**mentary (碎片的)}} of {{mediated||mediate||**adj. 间接的** \`ˈmiːdieɪt\` intervene between people in a dispute in order to bring about an agreement or reconciliation||语源“居于中间”: ***medi-*** (middle) + ***-ate*** (forming adj., 表性质)||***medi-*** (middle) → **medi**um (媒介), **medi**an (中间值)}} experiences. And reading, in particular, is an important exercise in {{inferiority||inferiority||**n. 自卑** \`ɪnˌfɪriˈɔːrəti\` *(inferiority to)* the condition of being lower in status or quality than another or others||语源“更低下”: ***infer-*** (below) + ***-ior*** (forming adj., 表比较级) + ***-ity*** (forming n., 表性质)||***infer-*** (below) → **infer**nal (地狱的), **infra**structure (基础设施)}}, an {{insistence||insistence||**n. 坚持** \`ɪnˈsɪstəns\` the act of declaring something firmly||语源“坚持”: ***in-*** (on) + ***sist*** (stand) + ***-ence*** (forming n., 表状态)||***sist*** (stand) → **sist**er (姐妹), con**sist** (组成)}} on listening to something without {{imposing||impose||**v. 强加** \`ɪmˈpoʊz\` *(impose on)* force (something unwelcome or unfamiliar) to be accepted or put in place||语源“放置于上”: ***im-*** (on) + ***pose*** (put, place)||***pose*** (put, place) → de**pose** (罢免), com**pose** (组成)}} your own design on it. It’s a grounding and an {{ascension||ascension||**n. 上升** \`əˈsɛnʃən\` the act of rising to an important position or a higher level||语源“向上攀登”: ***ad-*** (to) + ***scend*** (climb) + ***-sion*** (forming n., 表状态)||***scend*** (climb) → de**scend** (下降), tran**scend** (超越)}}. While we still have the institutions of school and class time as well as the books that line our walls, we need to challenge students with language and characters that may not come to them immediately but might with healthy discipline.

The {{notion||notion||**n. 概念** \`ˈnoʊʃən\` a conception of or belief about something||语源“知道”: ***gno*** (know) + ***-tion*** (forming n., 表状态)||***gno*** (know) → **know** (知道), **gno**sis (灵知)}} that students can master a range of literary {{competencies||competency||**n. 能力** \`ˈkɑːmpɪtənsi\` the ability to do something successfully or efficiently||语源“胜任”: ***com-*** (together) + ***pet*** (seek) + ***-ency*** (forming n., 表状态)||***pet*** (seek) → com**pet**e (竞争), re**peat** (重复)}} is further {{diluting||dilute||**v. 稀释** \`daɪˈluːt\` make (something) weaker in force, content, or value||语源“冲洗掉”: ***di-*** (apart) + ***lu*** (wash) + ***-te*** (forming v., 表动作)||***lu*** (wash) → de**luge** (洪水), a**blu**tion (沐浴)}} the already {{deluded||delude||**adj. 受迷惑的** \`dɪˈluːd\` deceive (someone)||语源“欺骗”: ***de-*** (down) + ***lud*** (play)||***lud*** (play) → pre**lude** (序幕), e**lude** (逃避)}} approach to English class. To put the National Council of Teachers of English guidelines in action, teachers are {{substituting||substitute||**v. 代替** \`ˈsʌbstɪtuːt\` *(substitute for)* use or add in place of something else||语源“置于之下”: ***sub-*** (under) + ***stat*** (stand) + ***-ute*** (forming v., 表动作)||***stat*** (stand) → con**stat**nt (不变的), **stat**ionary (静止的)}} {{intertextuality||intertextuality||**n. 互文性** \`ˌɪntərˌtɛkstʃuˈæləti\` the relationship between texts, especially literary ones}} and {{experiential||experiential||**adj. 体验的** \`ɪkˌspɪriˈɛnʃəl\` involving or based on experience and observation||语源“经验的”: ***ex-*** (out) + ***per*** (try) + ***-ience*** (forming n., 表状态) + ***-al*** (forming adj.)||***per*** (try) → ex**per**iment (实验), ex**per**t (专家)}} learning for engaging with the actual text. What might have been a full read of “The Great Gatsby” is replaced by students reading the first three chapters, then listening to a TED Talk on the American dream, reading a Claude McKay poem, dressing up like flappers and then writing and delivering a PowerPoint presentation on Prohibition. They’ll experience Chapters 4 through 8 only through plot summaries and return to their texts for the final chapter.

Going mostly by summary and assumption, students get {{thumbnail||thumbnail||**adj. 缩略的** \`ˈθʌmneɪl\` a small or concise description}} versions of things. They see the Cartesian grid, the lines on a map that chart the ocean, but they “don’t see the waves,” as the media theorist Douglas Rushkoff recently said about the reality in which many seem to be living in now. They see “the {{metrics||metric||**n. 指标** \`ˈmɛtrɪk\` a system or standard of measurement||语源“测量”: ***metr*** (measure) + ***-ic*** (forming adj., 表性质)||***metr*** (measure) → **meter** (米), **metr**onomy (节拍器)}} that can be measured rather than the reality that those metrics are simply trying to {{approximate||approximate||**v. 接近** \`əˈprɑːksɪmeɪt\` be close or similar to (something) in quality, nature, or quantity||语源“靠近”: ***ad-*** (to) + ***proxim*** (near) + ***-ate*** (forming v., 表动作)||***proxim*** (near) → **proxim**ity (接近), ap**proach** (接近)}}.” He is not an {{alarmist||alarmist||**n. 危言耸听者** \`əˈlɑːrmɪst\` a person who exaggerates a danger and so causes needless worry or panic}}, but he is alarmed about losing the “in-between, this {{connective||connective||**adj. 连接的** \`kəˈnɛktɪv\` used or able to connect||语源“连接的”: ***con-*** (together) + ***nect*** (bind) + ***-ive*** (forming adj., 表性质)||***nect*** (bind) → an**nex** (兼并), **nex**us (连接)}} reality.”

Of all the things I could do in this world, I’m fortunate to {{peddle||peddle||**v. 兜售** \`ˈpɛdl\` try to sell (something, especially small goods) by going from place to place}} stories from faraway lands to young minds and see whether I can {{rouse||rouse||**v. 唤起** \`raʊz\` awaken (someone) from sleep}} their {{synapses||synapse||**n. 神经突触** \`ˈsɪnæps\` a junction between nerve cells}} . Sometimes, I’ll admit, I’d rather be watching sports or “Saturday Night Live” clips or sleeping, even. And it’s not easy for students to crack open a book, to {{decipher||decipher||**v. 解码** \`dɪˈsaɪfər\` succeed in understanding, interpreting, or identifying (something)||语源“解开密码”: ***de-*** (reverse) + ***cipher*** (code)||***cipher*** (code) → en**cipher** (加密)}} language written in a way they don’t speak and to {{codify||codify||**v. 编纂** \`ˈkoʊdɪfaɪ\` arrange (laws or rules) into a systematic code||语源“编成法典”: ***cod-*** (code) + ***-ify*** (forming v., ……化, 表状态改变)||***cod-*** (code) → **code** (代码)}} {{multisyllabic||multisyllabic||**adj. 多音节的** \`ˌmʌltisɪˈlæbɪk\` having more than one syllable}}. (It’s also not easy for them to wake up at 5:30 for hockey practice, but they’re really good at this.)

The juniors and seniors I taught last fall had little knowledge of environmental activism or animal welfare when I handed them Richard Powers’s “Bewilderment,” about a {{precocious||precocious||**adj. 早熟的** \`prɪˈkoʊʃəs\` having developed certain abilities or proclivities at an earlier age than usual||语源“提前煮熟的”: ***pre-*** (before) + ***coc*** (cook) + ***-ious*** (forming adj., 表性质)||***coc*** (cook) → **cook** (烹饪), **coct**ion (烹调)}} 9-year-old who is {{consumed||consume||**adj. 充满的** \`kənˈsuːm\` *(be consumed with)* filled with a strong feeling}} with saving endangered species as his grieving father struggles to protect him. But the {{vicarious||vicarious||**adj. 间接的** \`vaɪˈkeriəs\` experienced in the imagination through the feelings or actions of another person||语源“替代的”: ***vic-*** (substitute) + ***-arious*** (forming adj., 表性质)||***vic-*** (substitute) → **vice** (代理), **vic**eroy (总督)}} safety of fiction gave students an invitation to discuss planetary ethics and the power and limits of parental love. This {{pathos||pathos||**n. 感染力** \`ˈpeɪθɑːs\` a quality that evokes pity or sadness||语源“情感”: ***path-*** (feeling) + ***-os*** (forming n., 表状态)||***path-*** (feeling) → **path**etic (可悲的), em**pathy** (共情)}} they raised will be a part of their forming identities. Had they merely read the summary, they would have seen many of the same words, but they’d have lacked the feeling part.

When a semester begins, I often give my students a {{wicked||wicked||**adj. 刁钻的** \`ˈwɪkɪd\` evil or morally wrong}} little essay by Virginia Woolf, “How Should One Read a Book?” She advises, “Begin not by sitting on the bench among the judges, but by standing in the dock with the criminal. Be his fellow worker, become his {{accomplice||accomplice||**n. 同谋** \`əˈkɑːmplɪs\` a person who helps another commit a crime||语源“同伙”: ***ac-*** (to) + ***com-*** (together) + ***plic*** (fold) + ***-ice*** (forming n., 表状态)||***plic*** (fold) → com**plic**ate (使复杂), im**plic**it (含蓄的)}}.” Like this, a classroom allows students to travel along with dockworkers and {{tycoons||tycoon||**n. 大亨** \`taɪˈkuːn\` a wealthy and powerful businessperson}}, {{tyrants||tyrant||**n. 暴君** \`ˈtaɪrənt\` a cruel and oppressive ruler}} and {{liberators||liberator||**n. 解放者** \`ˈlɪbəreɪtər\` a person who frees people from oppression, captivity, or restraint||语源“解放者”: ***liber*** (free) + ***-ator*** (forming n., 表人)||***liber*** (free) → **liber**ty (自由), de**liver** (交付)}}. And when they have turned the last page, Woolf invites the reader to “leave the dock and mount the bench. He must cease to be the friend; he must become the judge.”
                        `} />
                    </article>
                </div>
            </div>
        </div>
    )
}
